blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: 错误报告
    about: 报告 CloudX 行为异常、崩溃或规则未生效等问题
    title: "[BUG] "
    labels: bug
    body: ''
    
  - name: 功能请求
    about: 为 CloudX 提议新功能或改进
    title: "功能请求: "
    labels: enhancement
    body: ''

  - name: 文档请求
    about: 建议补充或改进 CloudX 文档 / README / 规则说明
    title: "文档建议: "
    labels: documentation
    body: ''

  - name: 实战经验征集 / 实现提交
    about: 分享或征集 CloudX 使用技巧 / 实战案例 / 踩坑总结 / 以及与本项目无关但涉及加解密的新技巧或思路；欢迎甲方/开发者提交实现/思路/技巧/想法
    title: "经验分享: "
    labels: experience
    body: ''
